version: 0.2


phases:
  build:
    commands:
      - ls -al
      - asciidoctor index.adoc -a outdir=.build -a imagesdir=images -a imagesoutdir=.build/images -a stylesheet=foundation.css -a stylesdir=/stylesheets/ -o .build/index.html -r asciidoctor-diagram

artifacts:
  files:
    - '*'
  base-directory: '.build/'